from pathlib import Path

path = Path("i18n/en.json")
text = path.read_text(encoding="utf-8")
text = text.replace('    "visualArt": "Visual Art Generator"', '    "visualArt": "Visual Art Generator",\r\n    "character": "Character Generator"')
insert_block = (
"  \"characterCreator\": {\r\n"
"    \"title\": \"Character Creator\",\r\n"
"    \"description\": \"Design characters and generate reference art with AI.\",\r\n"
"    \"changeViewMode\": \"Toggle view mode\",\r\n"
"    \"importCharacter\": \"Import character\",\r\n"
"    \"newCharacter\": \"New Character\",\r\n"
"    \"createNewCharacter\": \"Create New Character\",\r\n"
"    \"presets\": \"Presets\",\r\n"
"    \"characterName\": \"Character Name\",\r\n"
"    \"namePlaceholder\": \"e.g., John Smith\",\r\n"
"    \"role\": \"Role\",\r\n"
"    \"protagonist\": \"Protagonist\",\r\n"
"    \"supporting\": \"Supporting\",\r\n"
"    \"extra\": \"Extra\",\r\n"
"    \"characterStyle\": \"Character Style\",\r\n"
"    \"styleCinematic\": \"Cinematic\",\r\n"
"    \"stylePhotorealistic\": \"Photorealistic\",\r\n"
"    \"styleAnimation\": \"Animation\",\r\n"
"    \"styleAnime\": \"Anime\",\r\n"
"    \"styleConceptArt\": \"Concept Art\",\r\n"
"    \"physicalDescription\": \"Physical Description\",\r\n"
"    \"physicalDescriptionPlaceholder\": \"Describe appearance, build, and key features...\",\r\n"
"    \"clothingDescription\": \"Clothing Description\",\r\n"
"    \"clothingPlaceholder\": \"Describe outfit details...\",\r\n"
"    \"personalityTraits\": \"Personality Traits\",\r\n"
"    \"personalityPlaceholder\": \"Describe personality or demeanor...\",\r\n"
"    \"cancel\": \"Cancel\",\r\n"
"    \"create\": \"Create\",\r\n"
"    \"characterList\": \"Character List\",\r\n"
"    \"noCharactersYet\": \"No characters yet\",\r\n"
"    \"applyPresets\": \"Apply presets\",\r\n"
"    \"exportCharacter\": \"Export character\",\r\n"
"    \"imageGeneration\": \"Image Generation\",\r\n"
"    \"fullBodyReference\": \"Full Body Reference\",\r\n"
"    \"headshot\": \"Headshot\",\r\n"
"    \"customPromptPlaceholder\": \"Write a custom prompt...\",\r\n"
"    \"generate\": \"Generate\",\r\n"
"    \"generatingImage\": \"Generating image...\",\r\n"
"    \"additionalGeneratedImages\": \"Additional Generated Images\",\r\n"
"    \"selectOrCreateCharacter\": \"Select or create a character to get started.\",\r\n"
"    \"imageGenerationFailed\": \"Image generation failed\",\r\n"
"    \"cannotReadCharacterFile\": \"Could not read character file\"\r\n"
"  },\r\n"
"  \"characterPresets\": {\r\n"
"    \"title\": \"Character Preset Selector\",\r\n"
"    \"selectedCount\": \"{{count}} selected\",\r\n"
"    \"preview\": \"Preview\",\r\n"
"    \"clearAll\": \"Clear all\",\r\n"
"    \"searchPlaceholder\": \"Search presets...\",\r\n"
"    \"generatePrompt\": \"Generate Prompt\",\r\n"
"    \"previewTitle\": \"Selected Presets Preview\",\r\n"
"    \"generatedPrompt\": \"Generated Prompt:\",\r\n"
"    \"close\": \"Close\",\r\n"
"    \"applyPrompt\": \"Apply Prompt\",\r\n"
"    \"contextNew\": \"New character setup\",\r\n"
"    \"contextExisting\": \"Updating {{name}}\",\r\n"
"    \"contextExistingFallback\": \"Selected character\",\r\n"
"    \"noSelectionHint\": \"No presets selected yet. Choose a category to begin.\",\r\n"
"    \"noResults\": \"No presets match \\\"{{term}}\\\" in this category.\",\r\n"
"    \"promptHint\": \"Use these presets to instantly enrich descriptions or build AI prompts.\",\r\n"
"    \"categories\": {\r\n"
"      \"bodyType\": \"Body Type\",\r\n"
"      \"faceShape\": \"Face Shape\",\r\n"
"      \"ageRange\": \"Age Range\",\r\n"
"      \"hairStyle\": \"Hair Style\",\r\n"
"      \"clothingStyle\": \"Clothing Style\",\r\n"
"      \"personality\": \"Personality Traits\",\r\n"
"      \"accessories\": \"Accessories\",\r\n"
"      \"specialFeatures\": \"Special Features\"\r\n"
"    }\r\n"
"  },\r\n"
)
text = text.replace('  "inputForm": {', insert_block + '  "inputForm": {', 1)
path.write_text(text, encoding="utf-8")
