from pathlib import Path

path = Path("i18n/ko.json")
text = path.read_text(encoding="utf-8-sig")
text = text.replace('    "visualArt": "비주얼 아트 생성기"', '    "visualArt": "비주얼 아트 생성기",\r\n    "character": "캐릭터 생성기"')
insert_block = (
"  \"characterCreator\": {\r\n"
"    \"title\": \"캐릭터 생성기\",\r\n"
"    \"description\": \"AI로 캐릭터 정보를 정리하고 참고 이미지를 만들어 보세요.\",\r\n"
"    \"changeViewMode\": \"보기 모드 변경\",\r\n"
"    \"importCharacter\": \"캐릭터 가져오기\",\r\n"
"    \"newCharacter\": \"새 캐릭터\",\r\n"
"    \"createNewCharacter\": \"새 캐릭터 만들기\",\r\n"
"    \"presets\": \"프리셋\",\r\n"
"    \"characterName\": \"캐릭터 이름\",\r\n"
"    \"namePlaceholder\": \"예: 김하늘, Sarah\",\r\n"
"    \"role\": \"역할\",\r\n"
"    \"protagonist\": \"주인공\",\r\n"
"    \"supporting\": \"조연\",\r\n"
"    \"extra\": \"엑스트라\",\r\n"
"    \"characterStyle\": \"캐릭터 스타일\",\r\n"
"    \"styleCinematic\": \"시네마틱\",\r\n"
"    \"stylePhotorealistic\": \"포토리얼\",\r\n"
"    \"styleAnimation\": \"애니메이션\",\r\n"
"    \"styleAnime\": \"애니\",\r\n"
"    \"styleConceptArt\": \"컨셉 아트\",\r\n"
"    \"physicalDescription\": \"외형 묘사\",\r\n"
"    \"physicalDescriptionPlaceholder\": \"외형, 체형, 특징을 입력하세요...\",\r\n"
"    \"clothingDescription\": \"의상 묘사\",\r\n"
"    \"clothingPlaceholder\": \"착용하고 있는 옷을 설명하세요...\",\r\n"
"    \"personalityTraits\": \"성격 / 특징\",\r\n"
"    \"personalityPlaceholder\": \"성격이나 말투를 적어주세요...\",\r\n"
"    \"cancel\": \"취소\",\r\n"
"    \"create\": \"생성\",\r\n"
"    \"characterList\": \"캐릭터 목록\",\r\n"
"    \"noCharactersYet\": \"아직 생성한 캐릭터가 없습니다\",\r\n"
"    \"applyPresets\": \"프리셋 적용\",\r\n"
"    \"exportCharacter\": \"캐릭터 내보내기\",\r\n"
"    \"imageGeneration\": \"이미지 생성\",\r\n"
"    \"fullBodyReference\": \"전신 참고 이미지\",\r\n"
"    \"headshot\": \"헤드샷\",\r\n"
"    \"customPromptPlaceholder\": \"사용자 지정 프롬프트를 입력하세요...\",\r\n"
"    \"generate\": \"생성\",\r\n"
"    \"generatingImage\": \"이미지를 생성하는 중...\",\r\n"
"    \"additionalGeneratedImages\": \"추가 생성 이미지\",\r\n"
"    \"selectOrCreateCharacter\": \"캐릭터를 선택하거나 새로 만들어 시작하세요.\",\r\n"
"    \"imageGenerationFailed\": \"이미지 생성에 실패했습니다\",\r\n"
"    \"cannotReadCharacterFile\": \"캐릭터 파일을 읽을 수 없습니다\"\r\n"
"  },\r\n"
"  \"characterPresets\": {\r\n"
"    \"title\": \"캐릭터 프리셋 선택기\",\r\n"
"    \"selectedCount\": \"{{count}}개 선택됨\",\r\n"
"    \"preview\": \"미리보기\",\r\n"
"    \"clearAll\": \"모두 지우기\",\r\n"
"    \"searchPlaceholder\": \"프리셋 검색...\",\r\n"
"    \"generatePrompt\": \"프롬프트 생성\",\r\n"
"    \"previewTitle\": \"선택한 프리셋 미리보기\",\r\n"
"    \"generatedPrompt\": \"생성된 프롬프트:\",\r\n"
"    \"close\": \"닫기\",\r\n"
"    \"applyPrompt\": \"프롬프트 적용\",\r\n"
"    \"contextNew\": \"새 캐릭터 설정\",\r\n"
"    \"contextExisting\": \"{{name}} 캐릭터 업데이트\",\r\n"
"    \"contextExistingFallback\": \"선택된 캐릭터\",\r\n"
"    \"noSelectionHint\": \"프리셋을 선택해 캐릭터 정보를 구성하세요.\",\r\n"
"    \"noResults\": \"\\\"{{term}}\\\"에 해당하는 프리셋이 없습니다.\",\r\n"
"    \"promptHint\": \"선택한 프리셋으로 설명을 빠르게 채우거나 AI 프롬프트를 만들 수 있어요.\",\r\n"
"    \"categories\": {\r\n"
"      \"bodyType\": \"체형\",\r\n"
"      \"faceShape\": \"얼굴형\",\r\n"
"      \"ageRange\": \"연령대\",\r\n"
"      \"hairStyle\": \"헤어스타일\",\r\n"
"      \"clothingStyle\": \"의상 스타일\",\r\n"
"      \"personality\": \"성격 특징\",\r\n"
"      \"accessories\": \"액세서리\",\r\n"
"      \"specialFeatures\": \"특별한 특징\"\r\n"
"    }\r\n"
"  },\r\n"
)
text = text.replace('  "inputForm": {', insert_block + '  "inputForm": {', 1)
path.write_text(text, encoding="utf-8")
